name: Docker Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lighthouse-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Print Working Directory and List Files
        run: |
          echo Current directory:
          pwd
          echo Files in current directory:
          ls -l

      - name: Get LH version
        id: vars
        run: |
          LH_VERSION=$(jq -r .dependencies.lighthouse ./package.json | tr -d '^')
          echo "lh_version=$LH_VERSION" >> $GITHUB_OUTPUT

      - name: Test with Lighthouse and Puppeteer
        run: |
          docker run --rm -v "$PWD:$PWD" -w "$PWD" ibombit/lighthouse-puppeteer-chrome:${{ steps.vars.outputs.lh_version }}-alpine npx mocha ${{ secrets.TEST_PATH }} --browsertype=desktop --headless=true --url="https://demoqa.com/"

      - name: Upload report files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            ./reports/user-flow.report.html
            ./reports/user-flow.report.json